### ISSUE TITLE
bad interpreter

### ISSUE THREAD

**Issue by iamdevnull** [JayGoldberg/RSTunnel#21]
Here is a bug:

https://github.com/JayGoldberg/RSTunnel/blob/master/install.sh

-bash: ./install.sh: /bin/ash: bad interpreter: No such file or directory

**Comment by JayGoldberg** [comment]
Agreed, we shouldn't hard-code the shell. What shell are you actually using?

**Comment by iamdevnull** [comment]
> Agreed, we shouldn't hard-code the shell. What shell are you actually using?

I would use 

`#!/usr/bin/env bash` 

for portability

**Comment by JayGoldberg** [comment]
Not all embedded platforms seem to support `env`.

But `/bin/sh` seems guaranteed so I'll switch to that and test.

**Comment by iamdevnull** [comment]
sh will not work, because you are using bashism:

`./rstunnel: 254: [: unexpected operator
some of the paths do not exist
./rstunnel: 266: [: unexpected operator
some of the paths do not exist
./rstunnel: 266: [: unexpected operator
./rstunnel: 281: [: Linux: unexpected operator
./rstunnel: 281: [: Linux: unexpected operator
./rstunnel: 285: [: Linux: unexpected operator
[FATAL] Sorry, your OS is not supported.
`
from my point of view: use #!/usr/bin/env bash or #!/bin/bash

**Comment by JayGoldberg** [comment]
Yes, but the major point of this project is to avoid using bash so I need
to change the code to use lower level shell features.

**Comment by JayGoldberg** [comment]
Actually, leaving this closed and instead fixing the bashism in #22
